version: 2
updates:
    # Keep Python dependencies up to date
    - package-ecosystem: "pip"
      directory: "/"
      schedule:
          interval: "monthly"
      open-pull-requests-limit: 10
      assignees:
          - "Matt-Hadley"
      commit-message:
          prefix: "deps"
          include: "scope"
      labels:
          - "dependencies"
          - "python"

    # Keep GitHub Actions up to date
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "monthly"
      open-pull-requests-limit: 5
      assignees:
          - "Matt-Hadley"
      commit-message:
          prefix: "ci"
          include: "scope"
      labels:
          - "dependencies"
          - "github-actions"
