# Release Management - Automated Releases with Release Please
name: Release

on:
    push:
        branches: [main]

permissions:
    contents: write
    pull-requests: write
    issues: write # For labels
    id-token: write # For attestations
    attestations: write
    checks: write
    pages: write # For GitHub Pages

concurrency:
    group: release-${{ github.ref }}
    cancel-in-progress: false # Don't cancel releases

jobs:
    release-please:
        name: Release Please
        runs-on: ubuntu-latest
        timeout-minutes: 10
        outputs:
            releases_created: ${{ steps.release.outputs.releases_created }}
            tag_name: ${{ steps.release.outputs.tag_name }}
        steps:
            - uses: googleapis/release-please-action@v4
              id: release
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  release-type: python

            - name: Debug Release Please outputs
              run: |
                  echo "Releases created: '${{ steps.release.outputs.releases_created }}'"
                  echo "Tag name: '${{ steps.release.outputs.tag_name }}'"

    test-matrix:
        name: Test on Python ${{ matrix.python-version }}
        needs: release-please
        if: ${{ needs.release-please.outputs.releases_created == 'true' }}
        runs-on: ubuntu-latest
        timeout-minutes: 10
        strategy:
            matrix:
                python-version: ["3.11", "3.12", "3.13"]
        steps:
            - name: Checkout code
              uses: actions/checkout@v5
              with:
                  fetch-depth: 0

            - name: Setup environment
              uses: ./.github/actions/setup-environment
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cache/pip
                      .venv
                  key: ${{ runner.os }}-python-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}
                  restore-keys: |
                      ${{ runner.os }}-python-${{ matrix.python-version }}-
                      ${{ runner.os }}-python-

            - name: Run health check
              run: make health-check

    publish:
        name: Publish to PyPI
        needs: [release-please, test-matrix]
        if: ${{ needs.release-please.outputs.releases_created == 'true' }}
        runs-on: ubuntu-latest
        timeout-minutes: 10
        environment: pypi
        steps:
            - name: Checkout code
              uses: actions/checkout@v5
              with:
                  fetch-depth: 0

            - name: Setup environment
              uses: ./.github/actions/setup-environment

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cache/pip
                      .venv
                  key: ${{ runner.os }}-python-${{ hashFiles('pyproject.toml') }}
                  restore-keys: |
                      ${{ runner.os }}-python-

            - name: Run health check
              run: make health-check

            - name: Extract coverage percentage
              id: coverage
              continue-on-error: true
              run: |
                  if [ -f coverage.xml ]; then
                      COVERAGE=$(python -c "
                  import xml.etree.ElementTree as ET
                  try:
                      tree = ET.parse('coverage.xml')
                      root = tree.getroot()
                      line_rate = float(root.attrib['line-rate'])
                      print(f'{line_rate * 100:.0f}')
                  except:
                      print('0')
                  ")
                      echo "line-rate=$COVERAGE" >> $GITHUB_OUTPUT
                      echo "Coverage percentage: $COVERAGE%"
                  else
                      echo "line-rate=0" >> $GITHUB_OUTPUT
                      echo "Coverage file not found"
                  fi

            - name: Update coverage badge
              continue-on-error: true
              uses: schneegans/dynamic-badges-action@v1.7.0
              with:
                  auth: ${{ secrets.GIST_SECRET }}
                  gistID: ${{ secrets.GIST_ID }}
                  filename: coverage.json
                  label: coverage
                  message: ${{ steps.coverage.outputs.line-rate || 'N/A' }}%
                  valColorRange: ${{ steps.coverage.outputs.line-rate || '0' }}
                  maxColorRange: 100
                  minColorRange: 0
                  namedLogo: pytest

            - name: Upload release assets
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ needs.release-please.outputs.tag_name }}
                  files: |
                      dist/*.whl
                  fail_on_unmatched_files: true

            - name: Attest build artifacts
              continue-on-error: true
              uses: actions/attest-build-provenance@v3
              with:
                  subject-path: "dist/*.whl"

            - name: Publish to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  packages-dir: dist/
                  attestations: true

    publish-docs:
        name: Publish Documentation
        needs: [release-please, test-matrix, publish]
        if: ${{ needs.release-please.outputs.releases_created == 'true' }}
        runs-on: ubuntu-latest
        timeout-minutes: 10
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v5
              with:
                  fetch-depth: 0

            - name: Setup environment
              uses: ./.github/actions/setup-environment

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cache/pip
                      .venv
                  key: ${{ runner.os }}-python-docs-${{ hashFiles('pyproject.toml') }}
                  restore-keys: |
                      ${{ runner.os }}-python-docs-
                      ${{ runner.os }}-python-

            - name: Install documentation dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -e ".[docs,rs232]"

            - name: Build documentation
              run: mkdocs build --clean

            - name: Setup Pages
              uses: actions/configure-pages@v5

            - name: Upload documentation artifacts
              uses: actions/upload-pages-artifact@v4
              with:
                  path: ./site

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
